### PR TITLE
fix: catch connection errors when running benchmarks

### PR DESCRIPTION
**Pull request by neopostmodern**

### CODE REVIEW

**Comment by neopostmodern** [comment]
i think we should figure out a unified strategy for dealing with response states first (before merging this)

copying from slack:
> amending the above: i'm currently fixing the health-check implementation (we should really have unit tests with every PR...) and i'm running into similar conceptual problems – it now reports "timeout" for all the offline ai implementations.
> is there maybe a "standard" out there for response statuses?
> otherwise, should we draft something comprehensive to be shared by health check, solve case, and possibly other feature interactions?
> the ones that come to my mind right now:
> - offline (i.e. connection refused)
> - timeout
> - non-200 response code
> - 200 + bad response content (not JSON, JSON not compliant to schema)
> - 200 + valid JSON was responded, but contained an error field
> - for health checks: 200 + a field indicating the AI is intentionally offline
> - 200 + none of the above = okay

**Comment by maccinza** [comment]
> i think we should figure out a unified strategy for dealing with response states first (before merging this)
> 
> copying from slack:
> 
> > amending the above: i'm currently fixing the health-check implementation (we should really have unit tests with every PR...) and i'm running into similar conceptual problems – it now reports "timeout" for all the offline ai implementations.
> > is there maybe a "standard" out there for response statuses?
> > otherwise, should we draft something comprehensive to be shared by health check, solve case, and possibly other feature interactions?
> > the ones that come to my mind right now:
> > 
> > * offline (i.e. connection refused)
> > * timeout
> > * non-200 response code
> > * 200 + bad response content (not JSON, JSON not compliant to schema)
> > * 200 + valid JSON was responded, but contained an error field
> > * for health checks: 200 + a field indicating the AI is intentionally offline
> > * 200 + none of the above = okay

Looks like a good plan. My opinion:
  - Do we need/want to handle offline/timeout as separate cases? From the benchmark perspective the AI was not reachable in time on both cases. Is it just a way of being more verbose and possibly helping debugging the AIs implementations?
  - For `AI is intentionally offline`:
    (1) - If the AI will be "turned off" intentionally, this should be communicated and it should be removed from the ais being benchmarked in a benchmark session that has not been started yet.
    (2) - If nothing is communicated or the benchmark has already started, the AI requests would fail and it should be considered faulty for that particular benchmarking session.
     Was there any particular discussion/reason for covering this scenario separately?

**Comment by neopostmodern** [comment]
i guess you are right. it would be a tech solution for a non-tech problem (lack of communication), so i guess we shouldn't encourage that and rather rely on people communicating properly!

but is this exhaustive then?

1. offline (i.e. connection refused)
2. timeout
3. non-200 response code
4. 200 + bad response content (not JSON, JSON not compliant to schema)
5. 200 + valid JSON was responded, but contained an error field
6. 200 + none of the above = okay

also, aren't 3 and 5 the same somehow?

**Comment by maccinza** [comment]
> i guess you are right. it would be a tech solution for a non-tech problem (lack of communication), so i guess we shouldn't encourage that and rather rely on people communicating properly!
> 
> but is this exhaustive then?
> 
> 1. offline (i.e. connection refused)
> 2. timeout
> 3. non-200 response code
> 4. 200 + bad response content (not JSON, JSON not compliant to schema)
> 5. 200 + valid JSON was responded, but contained an error field
> 6. 200 + none of the above = okay
> 
> also, aren't 3 and 5 the same somehow?

Yep, I guess 3 and 5 are redundant. It should be only 3 as the ai should only return a 200 with valid json for a correct response, if the json contains an error field it should return a proper HTTP error code other than the 200 code.

**Comment by neopostmodern** [comment]
okay, so if there is a non-200 response code we do number 3 and include the error message for debugging purposes. 
if it's a 200 with an error field it will fail our validation (against a yet-to-be-defined-schema) -> it's an invalid response and thus like number 4
and we drop number 5

**Review by mzwiessele — APPROVED** [review]
LGTM!

**Pull request merged**
